// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"1":{"path":"/user","layout":false,"id":"1"},"2":{"name":"login","path":"/user/login","parentId":"1","id":"2"},"3":{"path":"/welcome","name":"欢迎页面","icon":"smile","parentId":"ant-design-pro-layout","id":"3"},"4":{"path":"/product","name":"产品管理","icon":"ReconciliationOutlined","parentId":"ant-design-pro-layout","id":"4"},"5":{"path":"/file","name":"资料管理","icon":"LinkOutlined","parentId":"ant-design-pro-layout","id":"5"},"6":{"path":"/news","name":"新闻管理","icon":"StarOutlined","parentId":"ant-design-pro-layout","id":"6"},"7":{"path":"/","redirect":"/welcome","parentId":"ant-design-pro-layout","id":"7"},"8":{"path":"*","layout":false,"id":"8"},"ant-design-pro-layout":{"id":"ant-design-pro-layout","path":"/","isLayout":true}} as const;
  return {
    routes,
    routeComponents: {
'1': React.lazy(() => import( './EmptyRoute')),
'2': React.lazy(() => import(/* webpackChunkName: "p__User__Login__index" */'@/pages/User/Login/index.tsx')),
'3': React.lazy(() => import(/* webpackChunkName: "p__Welcome" */'@/pages/Welcome.tsx')),
'4': React.lazy(() => import(/* webpackChunkName: "p__Product__index" */'@/pages/Product/index.tsx')),
'5': React.lazy(() => import(/* webpackChunkName: "p__File__index" */'@/pages/File/index.tsx')),
'6': React.lazy(() => import(/* webpackChunkName: "p__News__index" */'@/pages/News/index.tsx')),
'7': React.lazy(() => import( './EmptyRoute')),
'8': React.lazy(() => import(/* webpackChunkName: "p__404" */'@/pages/404.tsx')),
'ant-design-pro-layout': React.lazy(() => import(/* webpackChunkName: "t__plugin-layout__Layout" */'/Users/blue/Stations/zeliangongkong/admin/src/.umi-production/plugin-layout/Layout.tsx')),
},
  };
}
