// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import SmileOutlined from '/Users/blue/Stations/lingxn/admin/node_modules/.pnpm/@ant-design+icons@4.8.0_react-dom@18.2.0_react@18.2.0/node_modules/@ant-design/icons/es/icons/SmileOutlined';
import ReconciliationOutlined from '/Users/blue/Stations/lingxn/admin/node_modules/.pnpm/@ant-design+icons@4.8.0_react-dom@18.2.0_react@18.2.0/node_modules/@ant-design/icons/es/icons/ReconciliationOutlined';
import StarOutlined from '/Users/blue/Stations/lingxn/admin/node_modules/.pnpm/@ant-design+icons@4.8.0_react-dom@18.2.0_react@18.2.0/node_modules/@ant-design/icons/es/icons/StarOutlined';
import UserSwitchOutlined from '/Users/blue/Stations/lingxn/admin/node_modules/.pnpm/@ant-design+icons@4.8.0_react-dom@18.2.0_react@18.2.0/node_modules/@ant-design/icons/es/icons/UserSwitchOutlined';
import RadarChartOutlined from '/Users/blue/Stations/lingxn/admin/node_modules/.pnpm/@ant-design+icons@4.8.0_react-dom@18.2.0_react@18.2.0/node_modules/@ant-design/icons/es/icons/RadarChartOutlined';
import CodeSandboxOutlined from '/Users/blue/Stations/lingxn/admin/node_modules/.pnpm/@ant-design+icons@4.8.0_react-dom@18.2.0_react@18.2.0/node_modules/@ant-design/icons/es/icons/CodeSandboxOutlined';
export default { SmileOutlined, ReconciliationOutlined, StarOutlined, UserSwitchOutlined, RadarChartOutlined, CodeSandboxOutlined };
