// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import SmileOutlined from '/Users/blue/Stations/zeliangongkong/admin/node_modules/.pnpm/@ant-design+icons@4.8.0_react-dom@18.2.0_react@18.2.0/node_modules/@ant-design/icons/es/icons/SmileOutlined';
import ReconciliationOutlined from '/Users/blue/Stations/zeliangongkong/admin/node_modules/.pnpm/@ant-design+icons@4.8.0_react-dom@18.2.0_react@18.2.0/node_modules/@ant-design/icons/es/icons/ReconciliationOutlined';
import LinkOutlined from '/Users/blue/Stations/zeliangongkong/admin/node_modules/.pnpm/@ant-design+icons@4.8.0_react-dom@18.2.0_react@18.2.0/node_modules/@ant-design/icons/es/icons/LinkOutlined';
import StarOutlined from '/Users/blue/Stations/zeliangongkong/admin/node_modules/.pnpm/@ant-design+icons@4.8.0_react-dom@18.2.0_react@18.2.0/node_modules/@ant-design/icons/es/icons/StarOutlined';
export default { SmileOutlined, ReconciliationOutlined, LinkOutlined, StarOutlined };
